### ISSUE TITLE
Setup requirements

### ISSUE THREAD

**Issue by Oskar70** [jansaris/SolisToMqtt#1]
I am looking for something like this since two years. I only need the described values from my Solis-inverter an I know, that my wifi dongle can be used. 
I want to make use of this code on my raspi4. What software packages are generally required for making use of the code?

**Comment by jansaris** [comment]
Hi,
I used docker to run this application on my intel NUC.
But since last year I switched to a solution in Node-Red (integration on top of HomeAssistent) to get the data from my Inverter to inject in Home Assistent.
What is the setup you would like to achieve?

**Comment by Oskar70** [comment]
Hello Jan, thanks for replying.

I have a complete solution to measure overall consumption and delivery of electricity from/to grid and generation of electricity from my photovoltaik equipment. I have a Solis inverter (4,83 kWp) and Hoymiles inverters (2,55 kWp). To get data from the power meter I use Tasmota on a ESP8266 and MQTT and another ESP8266 and MQTT for the Hoymiles. The Solis Inverter was a nightmare for getting data. The Solis Support was incredible bad. I regret the lifetime it cost me to get the information I was asking for. After more than Emails (not klnowing your solution) The managed to send me a video which made me understand to read data from there cloud into Home Asssitant. Data from the Solis cloud do not come in a reliable sequence but days value (total yield at end of day) is ok. I did not want to use HA but I had to. Iam only using it to write Watt and total yield into influxdb.


Importing MQTT data and influxDB data from HA into node red-red, generating influxdb-output according to my needs, I use Grafana to display what I want (see examples attached).

I am using Synology NAS for all these tasks. I gave my solution to a friend, not having a Solis inverter and he is running it on a Raspberry Pi 4B (no HA needed).


Many words for your simple question. In addition to my NAS I also have a raspi and I want to use it instead of my NAS. I do not want to use HA on it. Therefore I need a possibility for direct import of Solis data via wifi stick such getting rid of Solis Cloud and HA. If there is a MQTT export in your solution I guess/hope that I can read it with the Mosquitto-MQTT Broker for transfer into node-red.

I am keen to get your answer.

If you are interested in details of my solution let me know and you can get it.

 


Gesendet: Sonntag, 23. Juni 2024 um 22:52 Uhr
Von: "Jan Saris" ***@***.***>
An: "jansaris/SolisToMqtt" ***@***.***>
Cc: "Oskar70" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jansaris/SolisToMqtt] Setup requirements (Issue #1)


 

Hi,
I used docker to run this application on my intel NUC.
But since last year I switched to a solution in Node-Red (integration on top of HomeAssistent) to get the data from my Inverter to inject in Home Assistent.
What is the setup you would like to achieve?

**Comment by Oskar70** [comment]
Hi Jan, just installed Maven (never heard about it before) on my raspi4 and in VSCode I added the Java Environment extension.  On my rasp I installed JDK 17.  I cloned your repository and tried to generate a runnnig version of it (Try and error, because never used Java-jar generation based Maven before). The first thing what popped up are 3 errors and 15 warnings. The three errors are from SolisReader.java:
The import javax.xml.ws cannot be resolved 
and 2 times
HTTPException cannot be reolved to a type.
In SolisToMqtt-main, there are two warnings which might be importent:
Build path specifies execution environment JvaSe-1.8. There are no JREs installed in the workspace that are strictly copatible.
The compiler compliance specified is 1.8 but a  JRE17 is used.
All other warnings are about never used and deprecated things.
I am still very keen to use your Solis2Mqqt program. So any hint or even better an updated repository and some hints for generating a complete solition would be very appreciated.
Byt he way, in my previous comment I reported about my nodered based things, but I now see, thta these pictures are not visible, so I try attaching these again as png-files instead of jpg. 
![PV-daywise](https://github.com/jansaris/SolisToMqtt/assets/124258121/586d95e1-dee8-42ce-9deb-196d6022a542)
![PV-monthwise](https://github.com/jansaris/SolisToMqtt/assets/124258121/43391e61-09bb-4389-971e-49c160adc7a5)

**Comment by jansaris** [comment]
[Zonnepanelen-flow.json](https://github.com/user-attachments/files/16039466/Zonnepanelen-flow.json)

Can you give this one a shot? If you have node-red already running, this should be fairly easy. You can simply import this json file in your node-red environment.
Enter your credentials and url in the first httprequest, so you connect to your local solis converter web page.
And in the last block you need to connect to your MQTT broker. The values will be posted on topic: tele/solis/SENSOR

**Comment by Oskar70** [comment]
Hello Jan,I tried it but one module was missing. In the meantime I ordered a Shelly 3em and the problem was solved. Comparing costs of shelly and the time I invested to enable direct access to the ginlong wifi dongle, I regret not to have purchased the shelly earlier. Thank you for your try to help.Wolfgang--Gesendet mit der WEB.DE Mail AppAm 29.06.24, 11:15 schrieb Jan Saris ***@***.***>:

   
  Zonnepanelen-flow.json 
  Can you give this one a shot? If you have node-red already running, this should be fairly easy. Enter your credentials and url in the first httprequest, so you connect to your local solis converter web page. And in the last block you need to connect to your MQTT broker. The values will be posted on topic: tele/solis/SENSOR
